source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftLuhn_Example', :exclusive => true do
  pod 'SwiftLuhn', :path => '../'
end

target 'SwiftLuhn_Tests', :exclusive => true do
  pod 'SwiftLuhn', :path => '../'

  
end
